packages:
  - "packages/*"
  - "apps/*"
  - "infra"

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - '@aws-sdk/client-secrets-manager@3.1092.0'
  - '@aws-sdk/client-sts@3.1092.0'
  - '@aws-sdk/core@3.976.0'
  - '@aws-sdk/credential-provider-env@3.972.60'
  - '@aws-sdk/credential-provider-http@3.972.62'
  - '@aws-sdk/credential-provider-ini@3.973.5'
  - '@aws-sdk/credential-provider-login@3.972.67'
  - '@aws-sdk/credential-provider-node@3.972.71'
  - '@aws-sdk/credential-provider-process@3.972.60'
  - '@aws-sdk/credential-provider-sso@3.973.4'
  - '@aws-sdk/credential-provider-web-identity@3.972.66'
  - '@aws-sdk/nested-clients@3.997.34'
  - '@aws-sdk/token-providers@3.1092.0'
