// Stable identifiers for the Boston Day 1 text slice.
// These are semantically immutable per docs/archive/2026-07/Localhost-Text-Slice-Spec.md §22.

export const PACKAGE_ID = "PA.BOSTON.DAY1.TEXT.v1";
export const SEASON_ID = "PA.SEA01.COLONIES.v1";
export const CHAPTER_ID = "PA.SEA01.CH02.BOSTON.v1";
export const MISSION_DAY_ID = "PA.SEA01.CH02.BOSTON.MD01.v1";

export const CONCEPTS = {
  POSTWAR_REVENUE: "BOS.MD01.CONCEPT.POSTWAR_REVENUE.v1",
  STAMP_SCOPE: "BOS.MD01.CONCEPT.STAMP_SCOPE.v1",
  REPRESENTATION: "BOS.MD01.CONCEPT.REPRESENTATION.v1",
} as const;

export type ConceptId = (typeof CONCEPTS)[keyof typeof CONCEPTS];

// Concept scheduling priority (spec §25 pending priority).
export const CONCEPT_PRIORITY: ConceptId[] = [
  CONCEPTS.STAMP_SCOPE,
  CONCEPTS.REPRESENTATION,
  CONCEPTS.POSTWAR_REVENUE,
];

export const RELATIONSHIPS = {
  ABIGAIL_TRUST: "BOS.CHAR.ABIGAIL.TRUST.v1",
  ABIGAIL_RESPECT: "BOS.CHAR.ABIGAIL.RESPECT.v1",
  ABIGAIL_WARMTH: "BOS.CHAR.ABIGAIL.WARMTH.v1",
  THOMAS_OBLIGATION: "BOS.CHAR.THOMAS.OBLIGATION.v1",
  PIKE_RESPECT: "BOS.CHAR.PIKE.RESPECT.v1",
  CLARKE_POLITICAL_READ: "BOS.CHAR.CLARKE.POLITICAL_READ.v1",
  RIDER_TRUST: "BOS.CHAR.RIDER.TRUST.v1",
} as const;

export const JOB_OBJECTS = {
  THOMAS_CIRCULAR: "BOS.MD01.OBJ.THOMAS_CIRCULAR.v1",
  PIKE_PROOF: "BOS.MD01.OBJ.PIKE_PROOF.v1",
  CARRIER_HANDBILLS: "BOS.MD01.OBJ.CARRIER_HANDBILLS.v1",
  CUSTOMHOUSE_NOTICE: "BOS.MD01.OBJ.CUSTOMHOUSE_NOTICE.v1",
  PLAIN_WRAP: "BOS.MD01.OBJ.PLAIN_WRAP.v1",
  RETAINED_STAMP_FORM: "BOS.MD01.OBJ.RETAINED_STAMP_FORM.v1",
  RETAINED_POLICY_SOURCE: "BOS.MD01.OBJ.RETAINED_POLICY_SOURCE.v1",
  RETAINED_REPRESENTATION_SOURCE: "BOS.MD01.OBJ.RETAINED_REPRESENTATION_SOURCE.v1",
} as const;

export const OBJECTIVE_GROUPS = {
  OPENING: "BOS.MD01.OBJECTIVES.OPENING.v1",
  ERRANDS: "BOS.MD01.OBJECTIVES.ERRANDS.v1",
  RIDER_ROUTE: "BOS.MD01.OBJECTIVES.RIDER_ROUTE.v1",
  EVENT_ONRAMP: "BOS.MD01.OBJECTIVES.EVENT_ONRAMP.v1",
  CLOSE: "BOS.MD01.OBJECTIVES.CLOSE.v1",
} as const;

// Canonical seed message (Backend-AI-System PA.RUN.SEED.v1).
export const RUN_SEED_MESSAGE_PREFIX = "PA.RUN.SEED.v1";
