// Ambient audio engine for the 1765-Boston world (World-Design-Bible §8).
// WebAudio only, no voiced dialogue anywhere. Zone beds crossfade (~1s) from
// the player's position, density scales with the clock phase (busier midday,
// sparse tense dusk), and one-shot events fire on warning-stage changes
// (church bell), portal crossings (door creak), and deterministic gull/dog/
// cart schedules. Files live in /public/audio (generated by
// assets/pipeline/gen_ambient_audio.mjs); if a file is missing or fails to
// decode the engine synthesizes a WebAudio fallback so sound always ships.
//
// Autoplay policy: the context is created muted on the first user gesture
// (pointerdown/keydown) and fades in; the HUD mute toggle persists to
// localStorage ("pa-audio-muted").

import { PROPS } from "./manifest.js";
import { mulberry32, hashString, zoneForPosition, type WorldZone } from "./atmosphere.js";
import { interiorDef } from "./interiorManifest.js";

type Phase = "MORNING" | "MIDDAY" | "AFTERNOON" | "DUSK";
type Warning = "NONE" | "FIRST" | "SECOND" | "FINAL";

export interface AudioWorldState {
  x: number;
  z: number;
  interiorId: string | null;
  phase: Phase;
  warningStage: Warning;
  rain: number; // 0..1 from the atmosphere schedule
  dusk: boolean;
}

const BED_NAMES = [
  "street-murmur",
  "market-clatter",
  "harbor-lap",
  "wind-gusts",
  "rain-bed",
  "room-tone",
  "press-shop",
  "church-hush",
  "tavern-walla",
  "warehouse-creak",
  "workshop-tools",
  "home-hearth",
  "civic-murmur",
  "ropework",
] as const;

const ONESHOT_NAMES = ["church-bell", "gull-cry", "cart-passby", "dog-bark", "door-creak"] as const;

type SoundName = (typeof BED_NAMES)[number] | (typeof ONESHOT_NAMES)[number];

const MUTE_KEY = "pa-audio-muted";
const MASTER_LEVEL = 0.9;
const CROSSFADE_TC = 0.35; // setTargetAtTime constant: ~1s to settle

function phaseDensity(phase: Phase): number {
  switch (phase) {
    case "MORNING": return 0.85;
    case "MIDDAY": return 1.0;
    case "AFTERNOON": return 0.8;
    case "DUSK": return 0.5;
  }
}

// ---- Synth fallbacks (compact WebAudio recipes; used when a file fails) -----
function synthBuffer(ctx: AudioContext, name: SoundName): AudioBuffer {
  const sr = ctx.sampleRate;
  const seconds = name === "church-bell" ? 6 : name === "door-creak" || name === "dog-bark" ? 2 : name === "gull-cry" ? 3 : 12;
  const buf = ctx.createBuffer(1, Math.round(sr * seconds), sr);
  const d = buf.getChannelData(0);
  const rnd = mulberry32(hashString(name));
  if (name === "church-bell") {
    const parts: [number, number, number][] = [[196, 0.5, 5], [392, 0.8, 3.5], [466, 0.6, 2.6], [784, 0.5, 1.3], [1175, 0.2, 0.7]];
    for (const [f, g, tau] of parts) {
      let ph = 0;
      for (let i = 0; i < d.length; i++) {
        const t = i / sr;
        ph += (2 * Math.PI * f) / sr;
        d[i] = (d[i] ?? 0) + Math.sin(ph) * g * Math.exp(-t / tau) * 0.28;
      }
    }
  } else if (name === "gull-cry") {
    for (const at of [0.15, 0.85]) {
      let ph = 0;
      for (let i = 0; i < sr * 0.5; i++) {
        const t = i / sr;
        const f = 1250 * (1.1 - 0.4 * (t / 0.5)) + 60 * Math.sin(2 * Math.PI * 30 * t);
        ph += (2 * Math.PI * f) / sr;
        const j = Math.round(at * sr) + i;
        if (j < d.length) d[j] = (d[j] ?? 0) + Math.sin(ph) * Math.exp(-t / 0.2) * 0.4;
      }
    }
  } else if (name === "dog-bark") {
    for (const at of [0.1, 0.5]) {
      let ph = 0;
      for (let i = 0; i < sr * 0.2; i++) {
        const t = i / sr;
        const f = 340 + 240 * Math.exp(-t * 22);
        ph += (2 * Math.PI * f) / sr;
        const j = Math.round(at * sr) + i;
        if (j < d.length) d[j] = (d[j] ?? 0) + (Math.sin(ph) + 0.5 * Math.sin(2 * ph)) * Math.exp(-t / 0.05) * 0.45;
      }
    }
  } else if (name === "door-creak") {
    let ph = 0;
    for (let i = 0; i < sr * 1.4; i++) {
      const t = i / sr;
      const f = 160 + 240 * (t / 1.4) + 24 * Math.sin(2 * Math.PI * 9 * t);
      ph += (2 * Math.PI * f) / sr;
      d[i] = Math.sin(ph) * 0.3 * Math.min(1, t * 8) * Math.exp(-t / 0.9);
    }
  } else {
    // noise-based beds: filter tone per name
    let lp = 0;
    const cutoff = name === "rain-bed" ? 0.28 : name === "wind-gusts" ? 0.045 : name === "harbor-lap" ? 0.06 : 0.035;
    for (let i = 0; i < d.length; i++) {
      const w = rnd() * 2 - 1;
      lp += cutoff * (w - lp);
      const t = i / sr;
      const swell =
        name === "harbor-lap"
          ? 0.4 + 0.6 * Math.max(0, Math.sin(2 * Math.PI * 0.24 * t)) ** 1.6
          : name === "wind-gusts"
            ? 0.45 + 0.55 * Math.max(0, Math.sin(2 * Math.PI * 0.06 * t)) ** 1.4
            : 0.8 + 0.2 * Math.sin(2 * Math.PI * 0.1 * t);
      d[i] = (name === "rain-bed" ? w * 0.35 + lp * 0.4 : lp * 2.4) * swell * 0.5;
    }
    // seamless-ish loop: fade the last 0.4s into silence symmetry with the head
    const fade = Math.round(sr * 0.4);
    for (let i = 0; i < fade; i++) {
      const wIn = i / fade;
      const head = d[i] ?? 0;
      const tail = d[d.length - fade + i] ?? 0;
      d[i] = head * wIn + tail * (1 - wIn);
      d[d.length - fade + i] = tail * wIn;
    }
  }
  return buf;
}

interface Bed {
  gain: GainNode;
  source: AudioBufferSourceNode;
  filter?: BiquadFilterNode;
}

class AmbientAudioEngine {
  private ctx: AudioContext | null = null;
  private master: GainNode | null = null;
  private beds = new Map<string, Bed>();
  private buffers = new Map<string, AudioBuffer>();
  private files: Record<string, string> = {};
  private manifestLoaded = false;
  private loading = false;
  private ready = false;
  private muted: boolean;
  private listeners = new Set<() => void>();
  private lastUpdateAt = 0;
  private lastWarning: Warning | null = null;
  private lastInteriorId: string | null | undefined = undefined;
  private lastZone: WorldZone | null = null;
  private lastChurchyardBellAt = -Infinity;
  private oneShotNextAt = new Map<string, number>();
  private oneShotRnd = mulberry32(hashString("boston-1765-ambient"));
  private state: AudioWorldState | null = null;

  constructor() {
    let storedMute = false;
    try {
      storedMute = typeof localStorage !== "undefined" && localStorage.getItem(MUTE_KEY) === "1";
    } catch {
      storedMute = false;
    }
    this.muted = storedMute;
    if (typeof window !== "undefined") {
      const unlock = () => {
        window.removeEventListener("pointerdown", unlock);
        window.removeEventListener("keydown", unlock);
        void this.unlock();
      };
      window.addEventListener("pointerdown", unlock);
      window.addEventListener("keydown", unlock);
    }
  }

  // ---- public API -----------------------------------------------------------
  getMuted(): boolean {
    return this.muted;
  }

  setMuted(muted: boolean): void {
    if (this.muted === muted) return;
    this.muted = muted;
    try {
      localStorage.setItem(MUTE_KEY, muted ? "1" : "0");
    } catch {
      // storage unavailable: session-only toggle
    }
    if (this.ctx && this.master) {
      const now = this.ctx.currentTime;
      this.master.gain.cancelScheduledValues(now);
      this.master.gain.setTargetAtTime(muted ? 0 : MASTER_LEVEL, now, 0.2);
    }
    this.emit();
  }

  subscribe = (fn: () => void): (() => void) => {
    this.listeners.add(fn);
    return () => this.listeners.delete(fn);
  };

  // Called every frame by AudioDirector; internally throttled.
  update(state: AudioWorldState): void {
    this.state = state;
    const now = performance.now();
    if (now - this.lastUpdateAt < 150) return;
    this.lastUpdateAt = now;
    // Portal + warning transitions are tracked even before audio unlock so a
    // stale toll doesn't fire the moment sound starts.
    const warningChanged = this.lastWarning !== null && this.lastWarning !== state.warningStage;
    const interiorChanged = this.lastInteriorId !== undefined && this.lastInteriorId !== state.interiorId;
    const previousWarning = this.lastWarning;
    this.lastWarning = state.warningStage;
    this.lastInteriorId = state.interiorId;
    const zone = zoneForPosition(state.x, state.z);
    const zoneChanged = this.lastZone !== null && this.lastZone !== zone;
    this.lastZone = zone;
    if (!this.ready || !this.ctx) return;

    if (warningChanged && state.warningStage !== "NONE" && previousWarning !== null) {
      const tolls = state.warningStage === "FIRST" ? 1 : state.warningStage === "SECOND" ? 2 : 3;
      this.playBellTolls(tolls);
    }
    if (interiorChanged) this.playOneShot("door-creak", 0.5);
    if (zoneChanged && zone === "CHURCHYARD" && now - this.lastChurchyardBellAt > 60000) {
      this.lastChurchyardBellAt = now;
      this.playBellTolls(1);
    }
    this.applyBedGains(state, zone);
    this.scheduleRandomOneShots(state, zone);
  }

  debugState(): { muted: boolean; ready: boolean; zone: string | null; beds: Record<string, number> } {
    const beds: Record<string, number> = {};
    for (const [name, bed] of this.beds) beds[name] = Number(bed.gain.gain.value.toFixed(3));
    return { muted: this.muted, ready: this.ready, zone: this.lastZone, beds };
  }

  playOneShot(name: SoundName, gain = 0.7): void {
    const ctx = this.ctx;
    const buffer = this.buffers.get(name);
    if (!ctx || !this.master || !buffer) return;
    const src = ctx.createBufferSource();
    src.buffer = buffer;
    const g = ctx.createGain();
    g.gain.value = gain;
    src.connect(g).connect(this.master);
    src.start();
  }

  // ---- internals --------------------------------------------------------------
  private emit(): void {
    for (const fn of this.listeners) fn();
  }

  private async unlock(): Promise<void> {
    if (this.loading || this.ready) return;
    this.loading = true;
    try {
      const Ctor: typeof AudioContext | undefined =
        window.AudioContext ??
        (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
      if (!Ctor) return;
      const ctx = new Ctor();
      this.ctx = ctx;
      await ctx.resume().catch(() => undefined);
      this.master = ctx.createGain();
      this.master.gain.value = 0;
      this.master.connect(ctx.destination);
      await this.loadManifest();
      await Promise.all(
        [...BED_NAMES, ...ONESHOT_NAMES].map(async (name) => {
          this.buffers.set(name, await this.loadBuffer(name));
        }),
      );
      for (const name of BED_NAMES) {
        const buffer = this.buffers.get(name);
        if (!buffer) continue;
        const source = ctx.createBufferSource();
        source.buffer = buffer;
        source.loop = true;
        const gain = ctx.createGain();
        gain.gain.value = 0;
        if (name === "street-murmur" || name === "rain-bed") {
          const filter = ctx.createBiquadFilter();
          filter.type = "lowpass";
          filter.frequency.value = 18000;
          source.connect(filter).connect(gain).connect(this.master);
          this.beds.set(name, { gain, source, filter });
        } else {
          source.connect(gain).connect(this.master);
          if (name === "church-hush" || name === "warehouse-creak") {
            const delay = ctx.createDelay(0.3);
            delay.delayTime.value = name === "church-hush" ? 0.14 : 0.085;
            const wet = ctx.createGain();
            wet.gain.value = name === "church-hush" ? 0.18 : 0.11;
            gain.connect(delay).connect(wet).connect(this.master);
          }
          this.beds.set(name, { gain, source });
        }
        source.start(ctx.currentTime + Math.random() * 0.2);
      }
      this.ready = true;
      // fade the whole mix in after the first gesture (autoplay-safe)
      const now = ctx.currentTime;
      this.master.gain.setTargetAtTime(this.muted ? 0 : MASTER_LEVEL, now + 0.05, 0.45);
      this.emit();
    } finally {
      this.loading = false;
    }
  }

  private async loadManifest(): Promise<void> {
    try {
      const res = await fetch("/audio/manifest.json");
      if (!res.ok) return;
      const data = (await res.json()) as { sounds?: { name: string; file: string }[] };
      for (const s of data.sounds ?? []) this.files[s.name] = s.file;
      this.manifestLoaded = true;
    } catch {
      // manifest missing: fall back to name.mp3/name.wav probing
    }
  }

  private async loadBuffer(name: SoundName): Promise<AudioBuffer> {
    const ctx = this.ctx!;
    const candidates = this.files[name]
      ? [`/audio/${this.files[name]}`]
      : this.manifestLoaded
        ? []
        : [`/audio/${name}.mp3`, `/audio/${name}.wav`];
    for (const url of candidates) {
      try {
        const res = await fetch(url);
        if (!res.ok) continue;
        const bytes = await res.arrayBuffer();
        return await ctx.decodeAudioData(bytes);
      } catch {
        // try the next candidate, then synthesize
      }
    }
    return synthBuffer(ctx, name);
  }

  private playBellTolls(count: number): void {
    for (let i = 0; i < count; i++) {
      window.setTimeout(() => this.playOneShot("church-bell", 0.65), i * 1700);
    }
  }

  private applyBedGains(state: AudioWorldState, zone: WorldZone): void {
    const ctx = this.ctx!;
    const density = phaseDensity(state.phase);
    const inside = state.interiorId !== null;
    const interior = state.interiorId ?? "";
    const isPress = interior === "MERCER_PRESS";
    const isChurch = interior.includes("CHURCH") && interior !== "CUSTOM_HOUSE";
    const profile = interiorDef(state.interiorId)?.audioProfile;
    // market clatter follows the market-stall props so it moves with the layout
    let market = 0;
    for (const p of PROPS) {
      if (p.glb !== "market-stall") continue;
      const dist = Math.hypot(state.x - p.pos[0], state.z - p.pos[2]);
      market = Math.max(market, 1 - dist / 17);
    }
    const targets: Record<(typeof BED_NAMES)[number], number> = {
      "street-murmur": inside
        ? 0.055 * density
        : (zone === "STREET" ? 0.6 : zone === "SQUARE" ? 0.72 : zone === "ALLEY" ? 0.2 : zone === "CHURCHYARD" ? 0.24 : 0.12) * density,
      "market-clatter": inside ? 0 : Math.max(0, market) * 0.75 * density,
      "harbor-lap": inside ? 0 : zone === "WHARF" ? 0.85 : 0,
      "wind-gusts": inside
        ? 0.04
        : 0.16 + (zone === "WHARF" ? 0.2 : zone === "ALLEY" ? 0.14 : 0) + state.rain * 0.08 + (state.dusk ? 0.06 : 0),
      "rain-bed": state.rain * (inside ? 0.18 : 0.8),
      "room-tone": inside ? (isPress ? 0.5 : isChurch ? 0.25 : 0.75) : 0,
      "press-shop": isPress ? 0.8 : 0,
      "church-hush": isChurch ? 0.8 : !inside && zone === "CHURCHYARD" ? 0.22 : 0,
      "tavern-walla": profile === "TAVERN" ? 0.72 * density : 0,
      "warehouse-creak": profile === "WAREHOUSE" ? 0.7 : 0,
      "workshop-tools": profile === "WORKSHOP" || profile === "SHOP" ? 0.5 * density : 0,
      "home-hearth": profile === "HOME" ? 0.55 : 0,
      "civic-murmur": profile === "CIVIC" ? 0.58 * density : 0,
      "ropework": profile === "ROPEWORK" ? 0.72 : 0,
    };
    const now = ctx.currentTime;
    for (const name of BED_NAMES) {
      const bed = this.beds.get(name);
      if (!bed) continue;
      bed.gain.gain.setTargetAtTime(targets[name], now, CROSSFADE_TC);
      if (bed.filter) {
        bed.filter.frequency.setTargetAtTime(inside ? 720 : 18000, now, 0.35);
      }
    }
  }

  private scheduleRandomOneShots(state: AudioWorldState, zone: WorldZone): void {
    const ctx = this.ctx!;
    const now = ctx.currentTime;
    const density = phaseDensity(state.phase);
    const inside = state.interiorId !== null;
    // Deterministic interval chains (seeded PRNG, Bible §8): same session
    // timeline -> same schedule. Quieter/sparser at dusk via density.
    const defs: { name: SoundName; min: number; range: number; gain: number; allowed: boolean }[] = [
      { name: "gull-cry", min: 7, range: 9, gain: 0.5, allowed: !inside && (zone === "WHARF" || state.x < -80) },
      { name: "gull-cry", min: 26, range: 30, gain: 0.28, allowed: !inside && zone !== "WHARF" },
      { name: "dog-bark", min: 24, range: 26, gain: 0.4, allowed: !inside },
      { name: "cart-passby", min: 34, range: 36, gain: 0.45, allowed: !inside && (zone === "STREET" || zone === "SQUARE") },
    ];
    defs.forEach((def, i) => {
      const key = `${def.name}#${i}`;
      const nextAt = this.oneShotNextAt.get(key) ?? now + (def.min + this.oneShotRnd() * def.range) * 0.4;
      if (now < nextAt) return;
      this.oneShotNextAt.set(key, now + (def.min + this.oneShotRnd() * def.range) / Math.max(0.35, density));
      if (def.allowed) this.playOneShot(def.name, def.gain);
    });
  }
}

export const ambientAudio = new AmbientAudioEngine();

// QA hook: lets scripted tours confirm the engine unlocked and which beds are
// audible without reaching into module internals.
declare global {
  interface Window {
    __paAmbientAudio?: { muted: boolean; ready: boolean; zone: string | null; beds: Record<string, number> };
  }
}
if (typeof window !== "undefined") {
  Object.defineProperty(window, "__paAmbientAudio", {
    get: () => ambientAudio.debugState(),
  });
}
