// The single import surface onto @pa/curriculum, plus the narrow port this
// package needs from it.
//
// THIS PACKAGE INVENTS NO IDENTIFIER SCHEME. The repository already holds at
// least eight ways of writing the same standard — `8.4(A)`, `8.4A`, `(4)(A)`,
// `8.4(A):STAMP_ACT`, `(4)(A)·Stamp Act`, `8.12`, bare clause ids,
// `BOS.MD01.CONCEPT.*`, `RCC.*`, `RCL.*`, `MICRO.*`, `TEKS.PENDING_SME_REVIEW` —
// and @pa/curriculum exists to collapse them onto one canonical registry with an
// alias table. A ninth invented on the reporting surface would be the worst of
// the set: this is the artifact a district reads, and a mastery row keyed by a
// private identifier is a row nobody can reconcile against the state's standards.
//
// So every standard printed by this package is the registry's canonical `SeCode`,
// and the only other spelling emitted is `formatBareLetter` — `8.4A` — which is
// generated by the registry's own formatter rather than by string surgery here,
// because a district's warehouse writes it that way.
//
// TWO HONESTY RULES CARRIED STRAIGHT THROUGH FROM THE REGISTRY.
//
// 1. A PARAPHRASE IS NEVER RENDERED AS THE STANDARD'S OWN WORDS. Exactly one of
//    Boston's 23 student expectations (8.4(A)) has verbatim cited text; for the
//    other 22 the repository never held it. `descriptionSource` says which one a
//    reader is looking at, on every row, and there is no field that could carry a
//    paraphrase without it. A teacher-facing report that quotes a fabricated
//    standard is a compliance problem, not a cosmetic one.
// 2. THE CONCEPT-TO-STANDARD MAPPING IS DRAFT. Nothing in the Boston seed holds
//    SME_APPROVED, so `reviewStatus` travels with the concept and becomes a claim
//    qualifier rather than being quietly dropped. See claim.ts.

import {
  ALL_CONCEPTS,
  REPORTING_CATEGORY_NAMES,
  UnknownChapterError,
  compareSeCodes,
  formatBareLetter,
  getConcept,
  getStudentExpectation,
  isCurriculumConceptId,
  isSeCode,
  resolveChapterId,
  type InstructionalConcept,
  type StudentExpectation,
} from "@pa/curriculum";

export {
  ASSESSMENT_BOSTON_CAPSTONE,
  CHAPTER_BOSTON,
  CURRICULUM_ASSESSMENT_IDS,
  CURRICULUM_CHAPTER_IDS,
  UnknownAssessmentError,
  UnknownChapterError,
  isCurriculumAssessmentId,
  isCurriculumChapterId,
  resolveAssessmentId,
  resolveChapterId,
  type CurriculumAssessmentId,
  type CurriculumChapterId,
} from "@pa/curriculum";

/** Where the printed description of a standard came from. */
export type StandardDescriptionSource =
  /** The standard's own words, with a citation behind them. */
  | "OFFICIAL_TEXT"
  /** Our paraphrase. Legal to show, never legal to attribute to the state. */
  | "WORKING_PARAPHRASE";

/** What reporting needs to know about one student expectation. */
export interface StandardDescriptor {
  /** Canonical spelling, e.g. `8.4(A)`. The primary key. */
  readonly seCode: string;
  /** `8.4A`. The spelling a district warehouse ingests, from the registry's formatter. */
  readonly seCodeBare: string;
  readonly reportingCategory: number;
  readonly reportingCategoryName: string;
  readonly standardType: "READINESS" | "SUPPORTING";
  readonly description: string;
  readonly descriptionSource: StandardDescriptionSource;
}

/** What reporting needs to know about one instructional concept. */
export interface ConceptDescriptor {
  readonly conceptId: string;
  /** Human label. A report keyed by identifier is a report nobody reads. */
  readonly label: string;
  /** The one standard this concept's mastery counts toward. */
  readonly parentSe: string;
  /** The named piece of that standard, when it enumerates clauses. */
  readonly parentClauseId: string | null;
  /**
   * Standards this concept also legitimately evidences. Listed, never counted:
   * rolling one concept's mastery into three standards would inflate coverage
   * threefold on exactly the surface where inflation is least acceptable.
   */
  readonly alsoEvidences: readonly string[];
  readonly reviewStatus: "DRAFT" | "OWNER_PROVIDED" | "SME_APPROVED";
}

/** The two questions reporting asks the curriculum. */
export interface StandardsSource {
  concept(conceptId: string): ConceptDescriptor | undefined;
  standard(seCode: string): StandardDescriptor | undefined;
}

function projectConcept(concept: InstructionalConcept): ConceptDescriptor {
  return {
    conceptId: concept.conceptId,
    label: concept.label,
    parentSe: concept.parentSe,
    parentClauseId: concept.parentClauseId,
    alsoEvidences: [...concept.secondarySeCodes],
    reviewStatus: concept.reviewStatus,
  };
}

function projectStandard(se: StudentExpectation): StandardDescriptor {
  const official = se.textStatus === "VERBATIM_CITED" && se.officialText !== null;
  return {
    seCode: se.code,
    seCodeBare: formatBareLetter(se.code),
    reportingCategory: se.reportingCategory,
    reportingCategoryName: REPORTING_CATEGORY_NAMES[se.reportingCategory],
    standardType: se.standardType,
    description: official ? (se.officialText as string) : se.workingDescription,
    descriptionSource: official ? "OFFICIAL_TEXT" : "WORKING_PARAPHRASE",
  };
}

/** The real registry as a `StandardsSource`. */
export function registryStandardsSource(): StandardsSource {
  return {
    concept: (conceptId) => {
      // The registry, not the id pattern, is the authority on what exists — but
      // the pattern guard is what narrows a plain string onto the branded key.
      if (!isCurriculumConceptId(conceptId)) return undefined;
      const concept = getConcept(conceptId);
      return concept ? projectConcept(concept) : undefined;
    },
    standard: (seCode) => {
      if (!isSeCode(seCode)) return undefined;
      const se = getStudentExpectation(seCode);
      return se ? projectStandard(se) : undefined;
    },
  };
}

/**
 * A `StandardsSource` over explicit lists.
 *
 * Exists so a test can build a four-concept fixture chapter without the 46-concept
 * Boston registry, and so a later chapter can register without this package
 * changing. `registryStandardsSource` is the real one.
 */
export function staticStandardsSource(input: {
  readonly concepts: readonly ConceptDescriptor[];
  readonly standards: readonly StandardDescriptor[];
}): StandardsSource {
  const concepts = new Map(input.concepts.map((entry) => [entry.conceptId, entry]));
  const standards = new Map(input.standards.map((entry) => [entry.seCode, entry]));
  return {
    concept: (conceptId) => concepts.get(conceptId),
    standard: (seCode) => standards.get(seCode),
  };
}

/**
 * Every concept a chapter's capstone scopes, in the registry's order.
 *
 * READ FROM THE REGISTRY, NEVER FROM THE STUDENT'S ROWS. A concept nobody could
 * ask has no `concept_mastery` row, so a report built from the rows alone would
 * omit exactly the concepts it most needs to name — and a concept missing from a
 * report is indistinguishable from a concept nobody noticed was missing.
 *
 * The filter matches `compileBlueprint` in @pa/assessment: assessable MACRO
 * concepts only. MICRO concepts are enrichment reached through the reactive
 * world, are never a gate, and reporting a student as owing one would be a
 * demand nobody made of them.
 *
 * THROWS `UnknownChapterError` RATHER THAN RETURNING AN EMPTY LIST. On this
 * surface an empty concept list is not a small report, it is a roster asserting
 * that thirty students owe nothing — and it was reachable, because the registry
 * once keyed Boston under an authoring spelling the caller did not use. A caller
 * whose chapter id came from a request checks `isCurriculumChapterId` first and
 * answers 404; a caller passing a constant should not be catching anything.
 */
export function registryChapterConceptIds(chapterId: string): readonly string[] {
  // Canonicalised rather than compared raw, so a superseded spelling reaches the
  // same concepts instead of matching none of them.
  const chapter = resolveChapterId(chapterId);
  if (chapter === null) throw new UnknownChapterError(chapterId);
  return ALL_CONCEPTS.filter(
    (concept) =>
      concept.owner.chapterId === chapter &&
      concept.assessable &&
      concept.tier === "MACRO",
  ).map((concept) => concept.conceptId);
}

/**
 * Order standards the way a Texas reader expects: 8.4(A) before 8.10(A), not
 * lexically. Delegated to the registry's comparator so the two cannot disagree.
 */
export function compareStandardCodes(left: string, right: string): number {
  if (!isSeCode(left) || !isSeCode(right)) return left.localeCompare(right);
  return compareSeCodes(left, right);
}

/** Every concept the registry holds. Used only by the alias-safety test. */
export function allRegisteredConceptIds(): readonly string[] {
  return ALL_CONCEPTS.map((concept) => concept.conceptId);
}
