// GENERATED by assets/pipeline/export_runtime_collision_manifest.mjs — DO NOT EDIT.
// Runtime-safe asset-local collision metadata. No GLB parsing occurs in browser.

export type RuntimeCollider =
  | { id: string; shape: "box"; center: [number, number, number]; half: [number, number, number]; yaw?: number; tags?: string[]; marginReason?: string }
  | { id: string; shape: "capsule"; a: [number, number, number]; b: [number, number, number]; radius: number; tags?: string[]; marginReason?: string }
  | { id: string; shape: "support"; polygon: [number, number][]; y: number; link: string | string[]; tags?: string[]; marginReason?: string }
  | { id: string; shape: "hazard"; polygon: [number, number][]; minY: number; maxY?: number; link: string | string[]; tags?: string[]; marginReason?: string };

export interface RuntimeCollisionAsset {
  assetKey: string;
  category: string | null;
  profile: string;
  pendingDoorContract: boolean;
  pendingInteriorPlacement: boolean;
  rawSize: [number, number, number] | null;
  fittedSize: [number, number, number] | null;
  colliders: RuntimeCollider[];
}

export const RUNTIME_COLLISION_METADATA: Record<string, RuntimeCollisionAsset> = {
  "balance-plank": {
    "assetKey": "balance-plank",
    "category": "prop",
    "profile": "compound",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8996313214302063,
      0.3671009987592697,
      0.523510068655014
    ],
    "fittedSize": [
      1.9,
      0.367,
      0.524
    ],
    "colliders": [
      {
        "id": "plank-top",
        "shape": "support",
        "polygon": [
          [
            -0.95,
            -0.262
          ],
          [
            0.95,
            -0.262
          ],
          [
            0.95,
            0.262
          ],
          [
            -0.95,
            0.262
          ]
        ],
        "y": 0.367,
        "link": "traversal",
        "tags": [
          "support",
          "walkable",
          "density"
        ]
      }
    ]
  },
  "barrel-group": {
    "assetKey": "barrel-group",
    "category": "prop",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.9000670909881592,
      0.8933884501457214,
      1.446011483669281
    ],
    "fittedSize": [
      2.6,
      1.222,
      1.979
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.611,
          0
        ],
        "half": [
          1.24,
          0.611,
          0.93
        ],
        "tags": [
          "obstacle"
        ]
      }
    ]
  },
  "bed-fourpost": {
    "assetKey": "bed-fourpost",
    "category": "interior",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": true,
    "rawSize": [
      1.320866346359253,
      1.896766185760498,
      1.6742899417877197
    ],
    "fittedSize": [
      1.321,
      1.897,
      1.674
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.949,
          0
        ],
        "half": [
          0.61,
          0.949,
          0.787
        ],
        "tags": [
          "obstacle",
          "provisional"
        ]
      }
    ]
  },
  "bldg-brick": {
    "assetKey": "bldg-brick",
    "category": "building",
    "profile": "solid",
    "pendingDoorContract": true,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.283111810684204,
      1.9041840434074402,
      1.1070298552513123
    ],
    "fittedSize": [
      6.065,
      9,
      5.232
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          4.5,
          0
        ],
        "half": [
          2.973,
          4.5,
          2.556
        ],
        "tags": [
          "obstacle",
          "building",
          "broadphase"
        ]
      }
    ]
  },
  "bldg-clapboard": {
    "assetKey": "bldg-clapboard",
    "category": "building",
    "profile": "solid",
    "pendingDoorContract": true,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.6681846380233765,
      1.9028964638710022,
      1.6467965245246887
    ],
    "fittedSize": [
      7.013,
      8,
      6.923
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          4,
          0
        ],
        "half": [
          3.447,
          4,
          3.402
        ],
        "tags": [
          "obstacle",
          "building",
          "broadphase"
        ]
      }
    ]
  },
  "bldg-counting": {
    "assetKey": "bldg-counting",
    "category": "building",
    "profile": "solid",
    "pendingDoorContract": true,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8756895661354065,
      1.6014201641082764,
      1.903944194316864
    ],
    "fittedSize": [
      8.866,
      7.57,
      9
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          3.785,
          0
        ],
        "half": [
          4.373,
          3.785,
          4.44
        ],
        "tags": [
          "obstacle",
          "building",
          "broadphase"
        ]
      }
    ]
  },
  "bldg-customhouse": {
    "assetKey": "bldg-customhouse",
    "category": "building",
    "profile": "solid",
    "pendingDoorContract": true,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.9009810090065002,
      1.4566278457641602,
      1.3751163482666016
    ],
    "fittedSize": [
      13.824,
      10.593,
      10
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          5.297,
          0
        ],
        "half": [
          6.852,
          5.297,
          4.94
        ],
        "tags": [
          "obstacle",
          "building",
          "broadphase"
        ]
      }
    ]
  },
  "bldg-printshop": {
    "assetKey": "bldg-printshop",
    "category": "building",
    "profile": "solid",
    "pendingDoorContract": true,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.6323992013931274,
      1.7540911436080933,
      1.9013489484786987
    ],
    "fittedSize": [
      6.868,
      7.38,
      8
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          3.69,
          0
        ],
        "half": [
          3.374,
          3.69,
          3.94
        ],
        "tags": [
          "obstacle",
          "building",
          "broadphase"
        ]
      }
    ]
  },
  "bldg-row-brick-a": {
    "assetKey": "bldg-row-brick-a",
    "category": "building",
    "profile": "solid",
    "pendingDoorContract": true,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.3637490272521973,
      1.899249255657196,
      1.2096530199050903
    ],
    "fittedSize": [
      6.462,
      9,
      5.732
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          4.5,
          0
        ],
        "half": [
          3.171,
          4.5,
          2.806
        ],
        "tags": [
          "obstacle",
          "building",
          "broadphase"
        ]
      }
    ]
  },
  "bldg-row-brick-b": {
    "assetKey": "bldg-row-brick-b",
    "category": "building",
    "profile": "solid",
    "pendingDoorContract": true,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.2690849900245667,
      1.8997071385383606,
      1.2723771333694458
    ],
    "fittedSize": [
      6.012,
      9,
      6.028
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          4.5,
          0
        ],
        "half": [
          2.946,
          4.5,
          2.954
        ],
        "tags": [
          "obstacle",
          "building",
          "broadphase"
        ]
      }
    ]
  },
  "bldg-row-clapboard-a": {
    "assetKey": "bldg-row-clapboard-a",
    "category": "building",
    "profile": "solid",
    "pendingDoorContract": true,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.0219449996948242,
      1.8990322947502136,
      1.192604124546051
    ],
    "fittedSize": [
      4.305,
      8,
      5.024
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          4,
          0
        ],
        "half": [
          2.093,
          4,
          2.452
        ],
        "tags": [
          "obstacle",
          "building",
          "broadphase"
        ]
      }
    ]
  },
  "bldg-row-clapboard-b": {
    "assetKey": "bldg-row-clapboard-b",
    "category": "building",
    "profile": "solid",
    "pendingDoorContract": true,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.3027719855308533,
      1.8995733261108398,
      1.1448161602020264
    ],
    "fittedSize": [
      5.487,
      8,
      4.821
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          4,
          0
        ],
        "half": [
          2.684,
          4,
          2.351
        ],
        "tags": [
          "obstacle",
          "building",
          "broadphase"
        ]
      }
    ]
  },
  "bldg-row-clapboard-c": {
    "assetKey": "bldg-row-clapboard-c",
    "category": "building",
    "profile": "solid",
    "pendingDoorContract": true,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.290235996246338,
      1.899603247642517,
      1.5955762267112732
    ],
    "fittedSize": [
      5.434,
      8,
      6.72
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          4,
          0
        ],
        "half": [
          2.657,
          4,
          3.3
        ],
        "tags": [
          "obstacle",
          "building",
          "broadphase"
        ]
      }
    ]
  },
  "bldg-row-shop": {
    "assetKey": "bldg-row-shop",
    "category": "building",
    "profile": "solid",
    "pendingDoorContract": true,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.1002879738807678,
      1.8993173837661743,
      1.2762901186943054
    ],
    "fittedSize": [
      5.214,
      9,
      6.048
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          4.5,
          0
        ],
        "half": [
          2.547,
          4.5,
          2.964
        ],
        "tags": [
          "obstacle",
          "building",
          "broadphase"
        ]
      }
    ]
  },
  "bldg-scaffold": {
    "assetKey": "bldg-scaffold",
    "category": "building",
    "profile": "solid",
    "pendingDoorContract": true,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8984150290489197,
      1.3438761830329895,
      1.8955402970314026
    ],
    "fittedSize": [
      5,
      3.539,
      4.992
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          1.77,
          0
        ],
        "half": [
          2.44,
          1.77,
          2.436
        ],
        "tags": [
          "obstacle",
          "building",
          "broadphase"
        ]
      }
    ]
  },
  "bldg-tavern": {
    "assetKey": "bldg-tavern",
    "category": "building",
    "profile": "solid",
    "pendingDoorContract": true,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8994849920272827,
      1.7067033052444458,
      1.244404137134552
    ],
    "fittedSize": [
      10.017,
      9,
      6.562
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          4.5,
          0
        ],
        "half": [
          4.949,
          4.5,
          3.221
        ],
        "tags": [
          "obstacle",
          "building",
          "broadphase"
        ]
      }
    ]
  },
  "bldg-townhouse-civic": {
    "assetKey": "bldg-townhouse-civic",
    "category": "building",
    "profile": "solid",
    "pendingDoorContract": true,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.5133709907531738,
      1.8982023000717163,
      1.311684012413025
    ],
    "fittedSize": [
      9.567,
      12,
      8.292
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          6,
          0
        ],
        "half": [
          4.724,
          6,
          4.086
        ],
        "tags": [
          "obstacle",
          "building",
          "broadphase"
        ]
      }
    ]
  },
  "bldg-warehouse-street": {
    "assetKey": "bldg-warehouse-street",
    "category": "building",
    "profile": "solid",
    "pendingDoorContract": true,
    "pendingInteriorPlacement": false,
    "rawSize": [
      0.9899519979953766,
      0.9081399738788605,
      1.8978683352470398
    ],
    "fittedSize": [
      4.173,
      3.828,
      8
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          1.914,
          0
        ],
        "half": [
          2.027,
          1.914,
          3.94
        ],
        "tags": [
          "obstacle",
          "building",
          "broadphase"
        ]
      }
    ]
  },
  "bldg-warehouse-wharf-a": {
    "assetKey": "bldg-warehouse-wharf-a",
    "category": "building",
    "profile": "solid",
    "pendingDoorContract": true,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.3670219779014587,
      1.7320971488952637,
      1.8978452682495117
    ],
    "fittedSize": [
      7.103,
      9,
      9.861
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          4.5,
          0
        ],
        "half": [
          3.492,
          4.5,
          4.871
        ],
        "tags": [
          "obstacle",
          "building",
          "broadphase"
        ]
      }
    ]
  },
  "bldg-warehouse-wharf-b": {
    "assetKey": "bldg-warehouse-wharf-b",
    "category": "building",
    "profile": "solid",
    "pendingDoorContract": true,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.0698710083961487,
      1.8996683359146118,
      1.078817069530487
    ],
    "fittedSize": [
      4.506,
      8,
      4.543
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          4,
          0
        ],
        "half": [
          2.193,
          4,
          2.212
        ],
        "tags": [
          "obstacle",
          "building",
          "broadphase"
        ]
      }
    ]
  },
  "bollard": {
    "assetKey": "bollard",
    "category": "prop",
    "profile": "capsule",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.1970229148864746,
      1.8997843265533447,
      1.0724981427192688
    ],
    "fittedSize": [
      1.197,
      1.9,
      1.072
    ],
    "colliders": [
      {
        "id": "post",
        "shape": "capsule",
        "a": [
          0,
          0.5,
          0
        ],
        "b": [
          0,
          0.5,
          0
        ],
        "radius": 0.5,
        "tags": [
          "obstacle",
          "post"
        ]
      }
    ]
  },
  "bookshelf-ledgers": {
    "assetKey": "bookshelf-ledgers",
    "category": "interior",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": true,
    "rawSize": [
      1.3663777112960815,
      1.8991538882255554,
      0.4502052664756775
    ],
    "fittedSize": [
      1.366,
      1.899,
      0.45
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.95,
          0
        ],
        "half": [
          0.633,
          0.95,
          0.175
        ],
        "tags": [
          "obstacle",
          "provisional"
        ]
      }
    ]
  },
  "buoy": {
    "assetKey": "buoy",
    "category": "clutter",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.2995074391365051,
      1.898135483264923,
      1.2018585801124573
    ],
    "fittedSize": [
      1.3,
      1.898,
      1.202
    ],
    "colliders": []
  },
  "candle-sconce": {
    "assetKey": "candle-sconce",
    "category": "interior",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": true,
    "rawSize": [
      1.6138954758644104,
      1.6003888249397278,
      1.8990641832351685
    ],
    "fittedSize": [
      1.614,
      1.6,
      1.899
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.8,
          0
        ],
        "half": [
          0.757,
          0.8,
          0.9
        ],
        "tags": [
          "obstacle",
          "provisional"
        ]
      }
    ]
  },
  "cargo-net-bundle": {
    "assetKey": "cargo-net-bundle",
    "category": "prop",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.2795450091362,
      1.89857679605484,
      1.0668876767158508
    ],
    "fittedSize": [
      0.809,
      1.2,
      0.674
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.6,
          0
        ],
        "half": [
          0.365,
          0.6,
          0.297
        ],
        "tags": [
          "obstacle"
        ]
      }
    ]
  },
  "church-meetinghouse": {
    "assetKey": "church-meetinghouse",
    "category": "building",
    "profile": "solid",
    "pendingDoorContract": true,
    "pendingInteriorPlacement": false,
    "rawSize": [
      0.6790930032730103,
      1.8991321325302124,
      1.0888810753822327
    ],
    "fittedSize": [
      5.364,
      15,
      8.6
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          7.5,
          0
        ],
        "half": [
          2.622,
          7.5,
          4.24
        ],
        "tags": [
          "obstacle",
          "building",
          "broadphase"
        ]
      }
    ]
  },
  "church-pew-block": {
    "assetKey": "church-pew-block",
    "category": "interior",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": true,
    "rawSize": [
      1.8962140679359436,
      0.5649760067462921,
      1.6755582690238953
    ],
    "fittedSize": [
      1.896,
      0.565,
      1.676
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.283,
          0
        ],
        "half": [
          0.898,
          0.283,
          0.788
        ],
        "tags": [
          "obstacle",
          "provisional"
        ]
      }
    ]
  },
  "church-pulpit": {
    "assetKey": "church-pulpit",
    "category": "interior",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": true,
    "rawSize": [
      1.6143437027931213,
      1.8988274335861206,
      1.0947535634040833
    ],
    "fittedSize": [
      1.614,
      1.899,
      1.095
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.95,
          0
        ],
        "half": [
          0.757,
          0.95,
          0.498
        ],
        "tags": [
          "obstacle",
          "provisional"
        ]
      }
    ]
  },
  "churchyard-fence": {
    "assetKey": "churchyard-fence",
    "category": "prop",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8983997106552124,
      0.703150063753128,
      0.10082085058093071
    ],
    "fittedSize": [
      2.97,
      1.1,
      0.158
    ],
    "colliders": [
      {
        "id": "panel",
        "shape": "box",
        "center": [
          0,
          0.55,
          0
        ],
        "half": [
          1.465,
          0.55,
          0.079
        ],
        "tags": [
          "obstacle",
          "fence"
        ]
      }
    ]
  },
  "city-block-rear-a": {
    "assetKey": "city-block-rear-a",
    "category": "skyline",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.9062371253967285,
      1.0853177905082703,
      0.7963517606258392
    ],
    "fittedSize": [
      1.906,
      1.085,
      0.796
    ],
    "colliders": []
  },
  "city-block-rear-b": {
    "assetKey": "city-block-rear-b",
    "category": "skyline",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.9029691219329834,
      1.1077388525009155,
      1.0407951474189758
    ],
    "fittedSize": [
      1.903,
      1.108,
      1.041
    ],
    "colliders": []
  },
  "city-block-rear-c": {
    "assetKey": "city-block-rear-c",
    "category": "skyline",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.9153603315353394,
      1.3293387293815613,
      1.9261478781700134
    ],
    "fittedSize": [
      1.915,
      1.329,
      1.926
    ],
    "colliders": []
  },
  "clerk-desk": {
    "assetKey": "clerk-desk",
    "category": "interior",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": true,
    "rawSize": [
      0.9692033529281616,
      1.9012446403503418,
      0.9595411717891693
    ],
    "fittedSize": [
      0.969,
      1.901,
      0.96
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.951,
          0
        ],
        "half": [
          0.435,
          0.951,
          0.43
        ],
        "tags": [
          "obstacle",
          "provisional"
        ]
      }
    ]
  },
  "coin-paper-set": {
    "assetKey": "coin-paper-set",
    "category": "clutter",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8998197317123413,
      0.10791914910078049,
      1.1818627715110779
    ],
    "fittedSize": [
      1.9,
      0.108,
      1.182
    ],
    "colliders": []
  },
  "colonial-alley-a": {
    "assetKey": "colonial-alley-a",
    "category": "surface",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      12,
      0.07000000029802322,
      6.5
    ],
    "fittedSize": [
      12,
      0.07,
      6.5
    ],
    "colliders": []
  },
  "colonial-alley-b": {
    "assetKey": "colonial-alley-b",
    "category": "surface",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      12,
      0.07000000029802322,
      6.5
    ],
    "fittedSize": [
      12,
      0.07,
      6.5
    ],
    "colliders": []
  },
  "colonial-civic-square": {
    "assetKey": "colonial-civic-square",
    "category": "surface",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      17,
      0.1261160559952259,
      20
    ],
    "fittedSize": [
      17,
      0.126,
      20
    ],
    "colliders": []
  },
  "colonial-door-kit": {
    "assetKey": "colonial-door-kit",
    "category": "prop",
    "profile": "compound",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.4387749433517456,
      2.153177456697449,
      0.3158261328935623
    ],
    "fittedSize": [
      1.439,
      2.153,
      0.316
    ],
    "colliders": [
      {
        "id": "jamb-l",
        "shape": "box",
        "center": [
          -0.64,
          1.025,
          0
        ],
        "half": [
          0.04,
          1.025,
          0.1
        ],
        "tags": [
          "obstacle",
          "door-frame",
          "static"
        ]
      },
      {
        "id": "jamb-r",
        "shape": "box",
        "center": [
          0.64,
          1.025,
          0
        ],
        "half": [
          0.04,
          1.025,
          0.1
        ],
        "tags": [
          "obstacle",
          "door-frame",
          "static"
        ]
      },
      {
        "id": "lintel",
        "shape": "box",
        "center": [
          0,
          2.105,
          0
        ],
        "half": [
          0.68,
          0.04,
          0.1
        ],
        "tags": [
          "obstacle",
          "door-frame",
          "static"
        ]
      },
      {
        "id": "recess",
        "shape": "box",
        "center": [
          0,
          1.015,
          -0.14
        ],
        "half": [
          0.59,
          1.015,
          0.09
        ],
        "tags": [
          "obstacle",
          "door-recess",
          "static",
          "occluder"
        ]
      },
      {
        "id": "leaf",
        "shape": "box",
        "center": [
          0,
          1,
          0
        ],
        "half": [
          0.56,
          1,
          0.05
        ],
        "tags": [
          "obstacle",
          "door-leaf",
          "dynamic"
        ],
        "marginReason": "Closed-state finite OBB; runtime rotates it about the Door_Leaf hinge origin and only opens passage after capsule clearance."
      }
    ]
  },
  "colonial-gutter-corner": {
    "assetKey": "colonial-gutter-corner",
    "category": "surface",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.5,
      0.07366271619684994,
      1.5
    ],
    "fittedSize": [
      1.5,
      0.074,
      1.5
    ],
    "colliders": []
  },
  "colonial-gutter-straight": {
    "assetKey": "colonial-gutter-straight",
    "category": "surface",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      20,
      0.07619384862482548,
      1.2999999523162842
    ],
    "fittedSize": [
      20,
      0.076,
      1.3
    ],
    "colliders": []
  },
  "colonial-liberty-courtyard": {
    "assetKey": "colonial-liberty-courtyard",
    "category": "surface",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      26,
      0.07644378580152988,
      19
    ],
    "fittedSize": [
      26,
      0.076,
      19
    ],
    "colliders": []
  },
  "colonial-street-a": {
    "assetKey": "colonial-street-a",
    "category": "surface",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      20,
      0.17642271518707275,
      20
    ],
    "fittedSize": [
      20,
      0.176,
      20
    ],
    "colliders": []
  },
  "colonial-street-b": {
    "assetKey": "colonial-street-b",
    "category": "surface",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      20,
      0.17642271518707275,
      20
    ],
    "fittedSize": [
      20,
      0.176,
      20
    ],
    "colliders": []
  },
  "colonial-street-c": {
    "assetKey": "colonial-street-c",
    "category": "surface",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      20,
      0.17642271518707275,
      20
    ],
    "fittedSize": [
      20,
      0.176,
      20
    ],
    "colliders": []
  },
  "colonial-street-endcap": {
    "assetKey": "colonial-street-endcap",
    "category": "surface",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      10,
      0.13657798618078232,
      20
    ],
    "fittedSize": [
      10,
      0.137,
      20
    ],
    "colliders": []
  },
  "colonial-street-junction": {
    "assetKey": "colonial-street-junction",
    "category": "surface",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      10,
      0.14657600224018097,
      20
    ],
    "fittedSize": [
      10,
      0.147,
      20
    ],
    "colliders": []
  },
  "colonial-wharf-apron": {
    "assetKey": "colonial-wharf-apron",
    "category": "surface",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      42,
      0.0769593701697886,
      34
    ],
    "fittedSize": [
      42,
      0.077,
      34
    ],
    "colliders": []
  },
  "colonial-wharf-boardwalk": {
    "assetKey": "colonial-wharf-boardwalk",
    "category": "surface",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      74,
      0.07663197442889214,
      6.5
    ],
    "fittedSize": [
      74,
      0.077,
      6.5
    ],
    "colliders": []
  },
  "colonial-wharf-pier-finger": {
    "assetKey": "colonial-wharf-pier-finger",
    "category": "surface",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      10,
      0.07659464981406927,
      9
    ],
    "fittedSize": [
      10,
      0.077,
      9
    ],
    "colliders": []
  },
  "colonial-yard-east-cap": {
    "assetKey": "colonial-yard-east-cap",
    "category": "surface",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      20,
      0.07646793965250254,
      60
    ],
    "fittedSize": [
      20,
      0.076,
      60
    ],
    "colliders": []
  },
  "colonial-yard-ground": {
    "assetKey": "colonial-yard-ground",
    "category": "surface",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      22,
      0.076418895740062,
      10
    ],
    "fittedSize": [
      22,
      0.076,
      10
    ],
    "colliders": []
  },
  "colonial-yard-perimeter": {
    "assetKey": "colonial-yard-perimeter",
    "category": "surface",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      226,
      0.07552579324692488,
      20
    ],
    "fittedSize": [
      226,
      0.076,
      20
    ],
    "colliders": []
  },
  "crate-mound": {
    "assetKey": "crate-mound",
    "category": "prop",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.899880051612854,
      1.2096011638641357,
      1.3731975555419922
    ],
    "fittedSize": [
      3.4,
      2.165,
      2.457
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          1.083,
          0
        ],
        "half": [
          1.62,
          1.083,
          1.148
        ],
        "tags": [
          "obstacle",
          "landable"
        ]
      }
    ]
  },
  "crate-stack": {
    "assetKey": "crate-stack",
    "category": "prop",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.901905357837677,
      1.368348240852356,
      1.4393023252487183
    ],
    "fittedSize": [
      2.6,
      1.871,
      1.968
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.936,
          0
        ],
        "half": [
          1.24,
          0.936,
          0.924
        ],
        "tags": [
          "obstacle",
          "landable"
        ]
      }
    ]
  },
  "dresser-shelves": {
    "assetKey": "dresser-shelves",
    "category": "interior",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": true,
    "rawSize": [
      1.0595371723175049,
      1.899889886379242,
      0.510431557893753
    ],
    "fittedSize": [
      1.06,
      1.9,
      0.51
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.95,
          0
        ],
        "half": [
          0.48,
          0.95,
          0.205
        ],
        "tags": [
          "obstacle",
          "provisional"
        ]
      }
    ]
  },
  "drying-line-rack": {
    "assetKey": "drying-line-rack",
    "category": "prop",
    "profile": "compound",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.897767722606659,
      1.344151496887207,
      0.7578984200954437
    ],
    "fittedSize": [
      2.6,
      1.842,
      1.038
    ],
    "colliders": [
      {
        "id": "frame-l",
        "shape": "capsule",
        "a": [
          -1.18,
          0.08,
          0
        ],
        "b": [
          -1.18,
          1.762,
          0
        ],
        "radius": 0.08,
        "tags": [
          "obstacle"
        ]
      },
      {
        "id": "frame-r",
        "shape": "capsule",
        "a": [
          1.18,
          0.08,
          0
        ],
        "b": [
          1.18,
          1.762,
          0
        ],
        "radius": 0.08,
        "tags": [
          "obstacle"
        ]
      }
    ]
  },
  "duck-beam-frame": {
    "assetKey": "duck-beam-frame",
    "category": "prop",
    "profile": "compound",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8993340730667114,
      1.1656804084777832,
      0.6642536818981171
    ],
    "fittedSize": [
      1.899,
      1.166,
      0.664
    ],
    "colliders": [
      {
        "id": "post-l",
        "shape": "capsule",
        "a": [
          -0.869,
          0.08,
          0
        ],
        "b": [
          -0.869,
          1.086,
          0
        ],
        "radius": 0.08,
        "tags": [
          "obstacle",
          "density"
        ]
      },
      {
        "id": "post-r",
        "shape": "capsule",
        "a": [
          0.87,
          0.08,
          0
        ],
        "b": [
          0.87,
          1.086,
          0
        ],
        "radius": 0.08,
        "tags": [
          "obstacle",
          "density"
        ]
      },
      {
        "id": "beam",
        "shape": "box",
        "center": [
          0,
          1.026,
          0
        ],
        "half": [
          0.95,
          0.14,
          0.332
        ],
        "tags": [
          "obstacle",
          "overhead",
          "duck"
        ]
      }
    ]
  },
  "effigy-boot": {
    "assetKey": "effigy-boot",
    "category": "prop",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.903438150882721,
      1.811356246471405,
      0.7834087908267975
    ],
    "fittedSize": [
      1.903,
      1.811,
      0.783
    ],
    "colliders": []
  },
  "effigy-oliver": {
    "assetKey": "effigy-oliver",
    "category": "prop",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      0.6954500079154968,
      1.8995487689971924,
      0.5259775221347809
    ],
    "fittedSize": [
      0.695,
      1.9,
      0.526
    ],
    "colliders": []
  },
  "fence-gate": {
    "assetKey": "fence-gate",
    "category": "prop",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.900303602218628,
      1.3896551132202148,
      0.36358894407749176
    ],
    "fittedSize": [
      2.872,
      2.1,
      0.549
    ],
    "colliders": [
      {
        "id": "leaf",
        "shape": "box",
        "center": [
          0,
          1.05,
          0
        ],
        "half": [
          1.406,
          1.05,
          0.275
        ],
        "tags": [
          "obstacle",
          "gate",
          "route-gated"
        ]
      }
    ]
  },
  "firewood-stack": {
    "assetKey": "firewood-stack",
    "category": "prop",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.896063208580017,
      1.4755864143371582,
      0.9809924960136414
    ],
    "fittedSize": [
      1.542,
      1.2,
      0.798
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.6,
          0
        ],
        "half": [
          0.721,
          0.6,
          0.349
        ],
        "tags": [
          "obstacle",
          "landable"
        ]
      }
    ]
  },
  "first-person-arms": {
    "assetKey": "first-person-arms",
    "category": "firstperson",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8989777565002441,
      0.8898636996746063,
      1.132223129272461
    ],
    "fittedSize": [
      1.899,
      0.89,
      1.132
    ],
    "colliders": []
  },
  "first-person-left-arm": {
    "assetKey": "first-person-left-arm",
    "category": "firstperson",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      0.8604787886142731,
      1.8987133502960205,
      1.8659477233886719
    ],
    "fittedSize": [
      0.86,
      1.899,
      1.866
    ],
    "colliders": []
  },
  "first-person-left-grip": {
    "assetKey": "first-person-left-grip",
    "category": "firstperson",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      0.6296572983264923,
      1.8995665907859802,
      0.925046443939209
    ],
    "fittedSize": [
      0.63,
      1.9,
      0.925
    ],
    "colliders": []
  },
  "first-person-right-arm": {
    "assetKey": "first-person-right-arm",
    "category": "firstperson",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.0085214376449585,
      1.7059248685836792,
      1.899741768836975
    ],
    "fittedSize": [
      1.009,
      1.706,
      1.9
    ],
    "colliders": []
  },
  "fish-flakes-rack": {
    "assetKey": "fish-flakes-rack",
    "category": "prop",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.9202900528907776,
      0.5459903478622437,
      1.1635478734970093
    ],
    "fittedSize": [
      2.311,
      0.657,
      1.4
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.329,
          0
        ],
        "half": [
          1.096,
          0.329,
          0.64
        ],
        "tags": [
          "obstacle"
        ]
      }
    ]
  },
  "gangplank": {
    "assetKey": "gangplank",
    "category": "prop",
    "profile": "compound",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.898967981338501,
      0.35164104402065277,
      0.36565259099006653
    ],
    "fittedSize": [
      3.6,
      0.667,
      0.693
    ],
    "colliders": [
      {
        "id": "deck",
        "shape": "support",
        "polygon": [
          [
            -1.75,
            -0.326
          ],
          [
            1.75,
            -0.326
          ],
          [
            1.75,
            0.326
          ],
          [
            -1.75,
            0.326
          ]
        ],
        "y": 0.2,
        "link": "world:wharf-deck",
        "tags": [
          "support",
          "walkable"
        ]
      }
    ]
  },
  "hand-cart": {
    "assetKey": "hand-cart",
    "category": "prop",
    "profile": "compound",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8983879089355469,
      1.2586737275123596,
      1.4946318864822388
    ],
    "fittedSize": [
      2.6,
      1.724,
      2.047
    ],
    "colliders": [
      {
        "id": "bed",
        "shape": "box",
        "center": [
          0,
          0.724,
          0
        ],
        "half": [
          1.1,
          0.586,
          0.844
        ],
        "tags": [
          "obstacle"
        ]
      }
    ]
  },
  "hay-cart": {
    "assetKey": "hay-cart",
    "category": "prop",
    "profile": "compound",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8988708853721619,
      0.8921995162963867,
      1.059686541557312
    ],
    "fittedSize": [
      3.4,
      1.598,
      1.897
    ],
    "colliders": [
      {
        "id": "bed",
        "shape": "box",
        "center": [
          0,
          0.799,
          0
        ],
        "half": [
          1.5,
          0.671,
          0.799
        ],
        "tags": [
          "obstacle"
        ]
      }
    ]
  },
  "hearth-mantel": {
    "assetKey": "hearth-mantel",
    "category": "interior",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": true,
    "rawSize": [
      1.8995981216430664,
      1.2223581075668335,
      1.1279447674751282
    ],
    "fittedSize": [
      1.9,
      1.222,
      1.128
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.611,
          0
        ],
        "half": [
          0.9,
          0.611,
          0.514
        ],
        "tags": [
          "obstacle",
          "provisional"
        ]
      }
    ]
  },
  "hitching-post": {
    "assetKey": "hitching-post",
    "category": "prop",
    "profile": "capsule",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.2563992738723755,
      1.8996894359588623,
      1.2566267848014832
    ],
    "fittedSize": [
      0.4,
      0.605,
      0.4
    ],
    "colliders": [
      {
        "id": "post",
        "shape": "capsule",
        "a": [
          0,
          0.18,
          0
        ],
        "b": [
          0,
          0.425,
          0
        ],
        "radius": 0.18,
        "tags": [
          "obstacle",
          "post"
        ],
        "marginReason": "fit target z=0.4 collapses the footprint; post radius intentionally near the fitted half-extent until the fit is widened"
      }
    ]
  },
  "infill-lean-to": {
    "assetKey": "infill-lean-to",
    "category": "building",
    "profile": "solid",
    "pendingDoorContract": true,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8994427919387817,
      1.4469563961029053,
      1.1531515717506409
    ],
    "fittedSize": [
      1.899,
      1.447,
      1.153
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.724,
          0
        ],
        "half": [
          0.89,
          0.724,
          0.517
        ],
        "tags": [
          "obstacle",
          "building",
          "density"
        ]
      }
    ]
  },
  "infill-service-shed": {
    "assetKey": "infill-service-shed",
    "category": "building",
    "profile": "solid",
    "pendingDoorContract": true,
    "pendingInteriorPlacement": false,
    "rawSize": [
      0.998138427734375,
      1.8996292352676392,
      0.8092061877250671
    ],
    "fittedSize": [
      0.998,
      1.9,
      0.809
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.95,
          0
        ],
        "half": [
          0.439,
          0.95,
          0.345
        ],
        "tags": [
          "obstacle",
          "building",
          "density"
        ]
      }
    ]
  },
  "iron-stove": {
    "assetKey": "iron-stove",
    "category": "interior",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": true,
    "rawSize": [
      1.899735450744629,
      1.2222391963005066,
      0.6364896893501282
    ],
    "fittedSize": [
      1.9,
      1.222,
      0.636
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.611,
          0
        ],
        "half": [
          0.9,
          0.611,
          0.268
        ],
        "tags": [
          "obstacle",
          "provisional"
        ]
      }
    ]
  },
  "liberty-elm": {
    "assetKey": "liberty-elm",
    "category": "prop",
    "profile": "compound",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8892441987991333,
      1.905745804309845,
      1.6869961619377136
    ],
    "fittedSize": [
      14,
      14.122,
      12.501
    ],
    "colliders": [
      {
        "id": "trunk",
        "shape": "capsule",
        "a": [
          0,
          0.6,
          0
        ],
        "b": [
          0,
          3.9,
          0
        ],
        "radius": 0.6,
        "tags": [
          "obstacle",
          "tree-trunk"
        ]
      },
      {
        "id": "root",
        "shape": "box",
        "center": [
          0,
          0.25,
          0
        ],
        "half": [
          1.1,
          0.25,
          1.1
        ],
        "tags": [
          "obstacle",
          "root"
        ]
      }
    ]
  },
  "market-awning": {
    "assetKey": "market-awning",
    "category": "prop",
    "profile": "compound",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.9003983736038208,
      1.5581251382827759,
      1.5663560628890991
    ],
    "fittedSize": [
      2.912,
      2.387,
      2.4
    ],
    "colliders": [
      {
        "id": "post-fl",
        "shape": "capsule",
        "a": [
          -1.336,
          0.06,
          -1.08
        ],
        "b": [
          -1.336,
          2.327,
          -1.08
        ],
        "radius": 0.06,
        "tags": [
          "obstacle"
        ]
      },
      {
        "id": "post-fr",
        "shape": "capsule",
        "a": [
          1.336,
          0.06,
          -1.08
        ],
        "b": [
          1.336,
          2.327,
          -1.08
        ],
        "radius": 0.06,
        "tags": [
          "obstacle"
        ]
      },
      {
        "id": "post-bl",
        "shape": "capsule",
        "a": [
          -1.336,
          0.06,
          1.08
        ],
        "b": [
          -1.336,
          2.327,
          1.08
        ],
        "radius": 0.06,
        "tags": [
          "obstacle"
        ]
      },
      {
        "id": "post-br",
        "shape": "capsule",
        "a": [
          1.336,
          0.06,
          1.08
        ],
        "b": [
          1.336,
          2.327,
          1.08
        ],
        "radius": 0.06,
        "tags": [
          "obstacle"
        ]
      }
    ]
  },
  "market-stall": {
    "assetKey": "market-stall",
    "category": "prop",
    "profile": "compound",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.894108533859253,
      1.1941405534744263,
      1.107534408569336
    ],
    "fittedSize": [
      2.6,
      1.639,
      1.52
    ],
    "colliders": [
      {
        "id": "counter",
        "shape": "box",
        "center": [
          0,
          0.623,
          0.274
        ],
        "half": [
          1.15,
          0.557,
          0.334
        ],
        "tags": [
          "obstacle"
        ]
      },
      {
        "id": "post-l",
        "shape": "capsule",
        "a": [
          -1.15,
          0.06,
          -0.61
        ],
        "b": [
          -1.15,
          1.579,
          -0.61
        ],
        "radius": 0.06,
        "tags": [
          "obstacle"
        ]
      },
      {
        "id": "post-r",
        "shape": "capsule",
        "a": [
          1.15,
          0.06,
          -0.61
        ],
        "b": [
          1.15,
          1.579,
          -0.61
        ],
        "radius": 0.06,
        "tags": [
          "obstacle"
        ]
      }
    ]
  },
  "notice-board": {
    "assetKey": "notice-board",
    "category": "prop",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.1265536546707153,
      1.8992568850517273,
      0.38926221430301666
    ],
    "fittedSize": [
      1.542,
      2.6,
      0.533
    ],
    "colliders": [
      {
        "id": "board",
        "shape": "box",
        "center": [
          0,
          1.3,
          0
        ],
        "half": [
          0.731,
          1.3,
          0.267
        ],
        "tags": [
          "obstacle"
        ]
      }
    ]
  },
  "organizer-crate-perch": {
    "assetKey": "organizer-crate-perch",
    "category": "prop",
    "profile": "compound",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.9040822982788086,
      1.5724795460700989,
      1.0317717790603638
    ],
    "fittedSize": [
      1.904,
      1.572,
      1.032
    ],
    "colliders": [
      {
        "id": "crate-body",
        "shape": "box",
        "center": [
          -0.15,
          0.45,
          0
        ],
        "half": [
          0.62,
          0.45,
          0.52
        ],
        "tags": [
          "solid"
        ]
      },
      {
        "id": "crate-top",
        "shape": "support",
        "polygon": [
          [
            -0.72,
            -0.5
          ],
          [
            0.42,
            -0.5
          ],
          [
            0.42,
            0.5
          ],
          [
            -0.72,
            0.5
          ]
        ],
        "y": 0.9,
        "link": "crate-body",
        "tags": [
          "support",
          "walkable"
        ]
      },
      {
        "id": "barrel",
        "shape": "capsule",
        "a": [
          0.72,
          0.23,
          0.24
        ],
        "b": [
          0.72,
          0.66,
          0.24
        ],
        "radius": 0.23,
        "tags": [
          "solid"
        ]
      }
    ]
  },
  "paper-satchel": {
    "assetKey": "paper-satchel",
    "category": "clutter",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8984253406524658,
      1.2415716052055359,
      1.13864266872406
    ],
    "fittedSize": [
      1.898,
      1.242,
      1.139
    ],
    "colliders": []
  },
  "press-common": {
    "assetKey": "press-common",
    "category": "interior",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": true,
    "rawSize": [
      1.905820608139038,
      1.6165668368339539,
      1.5552393794059753
    ],
    "fittedSize": [
      1.906,
      1.617,
      1.555
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.809,
          0
        ],
        "half": [
          0.903,
          0.809,
          0.727
        ],
        "tags": [
          "obstacle",
          "provisional"
        ]
      }
    ]
  },
  "printer-ink-balls": {
    "assetKey": "printer-ink-balls",
    "category": "clutter",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      0.3796112388372421,
      0.29932676343014464,
      0.15598182380199432
    ],
    "fittedSize": [
      0.38,
      0.299,
      0.156
    ],
    "colliders": []
  },
  "printshop-hanging-sign": {
    "assetKey": "printshop-hanging-sign",
    "category": "clutter",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.899808645248413,
      1.0644994378089905,
      0.1421772837638855
    ],
    "fittedSize": [
      1.9,
      1.064,
      0.142
    ],
    "colliders": []
  },
  "protest-banner": {
    "assetKey": "protest-banner",
    "category": "clutter",
    "profile": "capsule",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.0866926312446594,
      1.8991077542304993,
      0.17068998515605927
    ],
    "fittedSize": [
      1.087,
      1.899,
      0.171
    ],
    "colliders": [
      {
        "id": "carry-pole",
        "shape": "capsule",
        "a": [
          0,
          0.04,
          0
        ],
        "b": [
          0,
          1.85,
          0
        ],
        "radius": 0.04,
        "tags": [
          "solid"
        ]
      }
    ]
  },
  "protest-torch": {
    "assetKey": "protest-torch",
    "category": "clutter",
    "profile": "capsule",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      0.4349289983510971,
      1.8987352848052979,
      0.43876007199287415
    ],
    "fittedSize": [
      0.435,
      1.899,
      0.439
    ],
    "colliders": [
      {
        "id": "pole",
        "shape": "capsule",
        "a": [
          0,
          0,
          0
        ],
        "b": [
          0,
          1.7,
          0
        ],
        "radius": 0.05,
        "tags": [
          "solid"
        ]
      }
    ]
  },
  "roof-ramp-cart": {
    "assetKey": "roof-ramp-cart",
    "category": "prop",
    "profile": "compound",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8991020917892456,
      0.6957148611545563,
      0.9756350517272949
    ],
    "fittedSize": [
      3.2,
      1.172,
      1.644
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.586,
          0
        ],
        "half": [
          1.45,
          0.527,
          0.702
        ],
        "tags": [
          "obstacle"
        ]
      }
    ]
  },
  "roof-walk-board": {
    "assetKey": "roof-walk-board",
    "category": "prop",
    "profile": "compound",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.898389995098114,
      0.6971663534641266,
      0.6433244943618774
    ],
    "fittedSize": [
      1.898,
      0.697,
      0.643
    ],
    "colliders": [
      {
        "id": "plank-top",
        "shape": "support",
        "polygon": [
          [
            -0.9,
            -0.24
          ],
          [
            0.9,
            -0.24
          ],
          [
            0.9,
            0.24
          ],
          [
            -0.9,
            0.24
          ]
        ],
        "y": 0.32,
        "link": "traversal",
        "tags": [
          "support",
          "walkable",
          "density"
        ]
      },
      {
        "id": "rail-post-a",
        "shape": "capsule",
        "a": [
          -0.75,
          0.32,
          -0.24
        ],
        "b": [
          -0.75,
          0.64,
          -0.24
        ],
        "radius": 0.04,
        "tags": [
          "rail"
        ]
      },
      {
        "id": "rail-post-b",
        "shape": "capsule",
        "a": [
          0.75,
          0.32,
          -0.24
        ],
        "b": [
          0.75,
          0.64,
          -0.24
        ],
        "radius": 0.04,
        "tags": [
          "rail"
        ]
      }
    ]
  },
  "roof-walk-board-long": {
    "assetKey": "roof-walk-board-long",
    "category": "prop",
    "profile": "compound",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8993099331855774,
      0.47844675183296204,
      0.33472461998462677
    ],
    "fittedSize": [
      1.899,
      0.478,
      0.335
    ],
    "colliders": [
      {
        "id": "plank-top",
        "shape": "support",
        "polygon": [
          [
            -0.9,
            -0.13
          ],
          [
            0.9,
            -0.13
          ],
          [
            0.9,
            0.13
          ],
          [
            -0.9,
            0.13
          ]
        ],
        "y": 0.22,
        "link": "traversal",
        "tags": [
          "support",
          "walkable",
          "density"
        ]
      },
      {
        "id": "mid-trestle",
        "shape": "capsule",
        "a": [
          0,
          0.13,
          0
        ],
        "b": [
          0,
          0.22,
          0
        ],
        "radius": 0.13,
        "tags": [
          "support-leg"
        ]
      }
    ]
  },
  "rope-coil-large": {
    "assetKey": "rope-coil-large",
    "category": "prop",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8960313200950623,
      0.2491248920559883,
      1.8767800331115723
    ],
    "fittedSize": [
      1.3,
      0.171,
      1.287
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.086,
          0
        ],
        "half": [
          0.6,
          0.086,
          0.593
        ],
        "tags": [
          "obstacle",
          "landable"
        ]
      }
    ]
  },
  "rowboat": {
    "assetKey": "rowboat",
    "category": "ship",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.9012236595153809,
      0.47956763207912445,
      0.7241807878017426
    ],
    "fittedSize": [
      1.901,
      0.48,
      0.724
    ],
    "colliders": [
      {
        "id": "hull",
        "shape": "box",
        "center": [
          0,
          0.24,
          0
        ],
        "half": [
          0.911,
          0.24,
          0.332
        ],
        "tags": [
          "obstacle",
          "hull"
        ]
      }
    ]
  },
  "scaffold-low": {
    "assetKey": "scaffold-low",
    "category": "prop",
    "profile": "compound",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8988102674484253,
      1.6310660243034363,
      0.7278643846511841
    ],
    "fittedSize": [
      2.794,
      2.4,
      1.071
    ],
    "colliders": [
      {
        "id": "frame",
        "shape": "box",
        "center": [
          0,
          1.008,
          0
        ],
        "half": [
          1.297,
          1.008,
          0.436
        ],
        "tags": [
          "obstacle"
        ]
      },
      {
        "id": "platform",
        "shape": "support",
        "polygon": [
          [
            -1.297,
            -0.435
          ],
          [
            1.297,
            -0.435
          ],
          [
            1.297,
            0.436
          ],
          [
            -1.297,
            0.436
          ]
        ],
        "y": 2.016,
        "link": "frame",
        "tags": [
          "support",
          "walkable"
        ]
      }
    ]
  },
  "service-wall-corner": {
    "assetKey": "service-wall-corner",
    "category": "prop",
    "profile": "compound",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.784942090511322,
      1.0356585383415222,
      1.9060348868370056
    ],
    "fittedSize": [
      1.785,
      1.036,
      1.906
    ],
    "colliders": [
      {
        "id": "wing-x",
        "shape": "box",
        "center": [
          0,
          0.518,
          -0.419
        ],
        "half": [
          0.893,
          0.518,
          0.152
        ],
        "tags": [
          "obstacle",
          "density-barrier"
        ]
      },
      {
        "id": "wing-z",
        "shape": "box",
        "center": [
          -0.393,
          0.518,
          0
        ],
        "half": [
          0.143,
          0.518,
          0.953
        ],
        "tags": [
          "obstacle",
          "density-barrier"
        ]
      }
    ]
  },
  "service-wall-end": {
    "assetKey": "service-wall-end",
    "category": "prop",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.89756840467453,
      0.9160448908805847,
      0.5631748139858246
    ],
    "fittedSize": [
      1.898,
      0.916,
      0.563
    ],
    "colliders": [
      {
        "id": "panel",
        "shape": "box",
        "center": [
          0,
          0.458,
          0
        ],
        "half": [
          0.929,
          0.458,
          0.282
        ],
        "tags": [
          "obstacle",
          "density-barrier"
        ]
      }
    ]
  },
  "service-wall-straight": {
    "assetKey": "service-wall-straight",
    "category": "prop",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.9010595679283142,
      0.862162321805954,
      0.42197585105895996
    ],
    "fittedSize": [
      1.901,
      0.862,
      0.422
    ],
    "colliders": [
      {
        "id": "panel",
        "shape": "box",
        "center": [
          0,
          0.431,
          0
        ],
        "half": [
          0.931,
          0.431,
          0.211
        ],
        "tags": [
          "obstacle",
          "density-barrier"
        ]
      }
    ]
  },
  "ship-brig-hero": {
    "assetKey": "ship-brig-hero",
    "category": "ship",
    "profile": "compound",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8986989855766296,
      1.1843342781066895,
      0.5691990554332733
    ],
    "fittedSize": [
      1.899,
      1.184,
      0.569
    ],
    "colliders": [
      {
        "id": "hull",
        "shape": "box",
        "center": [
          0,
          0.355,
          0
        ],
        "half": [
          0.9,
          0.355,
          0.254
        ],
        "tags": [
          "obstacle",
          "hull"
        ]
      },
      {
        "id": "deck",
        "shape": "support",
        "polygon": [
          [
            -0.849,
            -0.234
          ],
          [
            0.85,
            -0.234
          ],
          [
            0.85,
            0.235
          ],
          [
            -0.849,
            0.235
          ]
        ],
        "y": 0.71,
        "link": "hull",
        "tags": [
          "support",
          "deck"
        ]
      }
    ]
  },
  "ship-sloop": {
    "assetKey": "ship-sloop",
    "category": "ship",
    "profile": "compound",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.897026240825653,
      1.3345096707344055,
      0.37216103076934814
    ],
    "fittedSize": [
      1.897,
      1.335,
      0.372
    ],
    "colliders": [
      {
        "id": "hull",
        "shape": "box",
        "center": [
          0,
          0.467,
          0
        ],
        "half": [
          0.899,
          0.467,
          0.156
        ],
        "tags": [
          "obstacle",
          "hull"
        ]
      },
      {
        "id": "deck",
        "shape": "support",
        "polygon": [
          [
            -0.848,
            -0.136
          ],
          [
            0.849,
            -0.136
          ],
          [
            0.849,
            0.136
          ],
          [
            -0.848,
            0.136
          ]
        ],
        "y": 0.934,
        "link": "hull",
        "tags": [
          "support",
          "deck"
        ]
      }
    ]
  },
  "ship-snow-background": {
    "assetKey": "ship-snow-background",
    "category": "ship",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8995446562767029,
      1.2247876524925232,
      0.5840031802654266
    ],
    "fittedSize": [
      1.9,
      1.225,
      0.584
    ],
    "colliders": [
      {
        "id": "hull",
        "shape": "box",
        "center": [
          0,
          0.429,
          0
        ],
        "half": [
          0.9,
          0.429,
          0.262
        ],
        "tags": [
          "obstacle",
          "hull"
        ]
      }
    ]
  },
  "shop-counter": {
    "assetKey": "shop-counter",
    "category": "interior",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": true,
    "rawSize": [
      1.9063531756401062,
      1.2452902793884277,
      1.0550196170806885
    ],
    "fittedSize": [
      1.906,
      1.245,
      1.055
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.623,
          0
        ],
        "half": [
          0.903,
          0.623,
          0.478
        ],
        "tags": [
          "obstacle",
          "provisional"
        ]
      }
    ]
  },
  "shop-counter-long": {
    "assetKey": "shop-counter-long",
    "category": "interior",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": true,
    "rawSize": [
      1.899766445159912,
      0.44931410253047943,
      0.38238343596458435
    ],
    "fittedSize": [
      1.9,
      0.449,
      0.382
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.225,
          0
        ],
        "half": [
          0.9,
          0.225,
          0.141
        ],
        "tags": [
          "obstacle",
          "provisional"
        ]
      }
    ]
  },
  "skyline-cluster-a": {
    "assetKey": "skyline-cluster-a",
    "category": "skyline",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.501920461654663,
      1.166197955608368,
      1.897916853427887
    ],
    "fittedSize": [
      1.502,
      1.166,
      1.898
    ],
    "colliders": []
  },
  "skyline-cluster-b": {
    "assetKey": "skyline-cluster-b",
    "category": "skyline",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8991268873214722,
      0.848422110080719,
      0.9305979311466217
    ],
    "fittedSize": [
      1.899,
      0.848,
      0.931
    ],
    "colliders": []
  },
  "skyline-cluster-c": {
    "assetKey": "skyline-cluster-c",
    "category": "skyline",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8228064179420471,
      1.2611806988716125,
      1.9108354449272156
    ],
    "fittedSize": [
      1.823,
      1.261,
      1.911
    ],
    "colliders": []
  },
  "spinning-wheel": {
    "assetKey": "spinning-wheel",
    "category": "interior",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": true,
    "rawSize": [
      1.7762100100517273,
      1.9007112979888916,
      0.7287948131561279
    ],
    "fittedSize": [
      1.776,
      1.901,
      0.729
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.951,
          0
        ],
        "half": [
          0.838,
          0.951,
          0.315
        ],
        "tags": [
          "obstacle",
          "provisional"
        ]
      }
    ]
  },
  "stone-steps": {
    "assetKey": "stone-steps",
    "category": "interior",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": true,
    "rawSize": [
      1.8978952765464783,
      0.775486022233963,
      1.6853627562522888
    ],
    "fittedSize": [
      1.898,
      0.775,
      1.685
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.388,
          0
        ],
        "half": [
          0.899,
          0.388,
          0.793
        ],
        "tags": [
          "obstacle",
          "provisional"
        ]
      }
    ]
  },
  "storage-chest": {
    "assetKey": "storage-chest",
    "category": "interior",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": true,
    "rawSize": [
      1.8992119431495667,
      0.6999451518058777,
      0.8272781372070312
    ],
    "fittedSize": [
      1.899,
      0.7,
      0.827
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.35,
          0
        ],
        "half": [
          0.9,
          0.35,
          0.364
        ],
        "tags": [
          "obstacle",
          "provisional"
        ]
      }
    ]
  },
  "street-dog": {
    "assetKey": "street-dog",
    "category": "prop",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      0.3724460005760193,
      1.2437855005264282,
      1.8991960287094116
    ],
    "fittedSize": [
      0.372,
      1.244,
      1.899
    ],
    "colliders": []
  },
  "street-lantern-bracket": {
    "assetKey": "street-lantern-bracket",
    "category": "prop",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.4254372715950012,
      1.8994519710540771,
      1.051364779472351
    ],
    "fittedSize": [
      1.051,
      1.4,
      0.775
    ],
    "colliders": []
  },
  "table-chairs-set": {
    "assetKey": "table-chairs-set",
    "category": "interior",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": true,
    "rawSize": [
      1.89704430103302,
      0.9224279522895813,
      1.4767886400222778
    ],
    "fittedSize": [
      1.897,
      0.922,
      1.477
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.461,
          0
        ],
        "half": [
          0.899,
          0.461,
          0.689
        ],
        "tags": [
          "obstacle",
          "provisional"
        ]
      }
    ]
  },
  "tankard-cluster": {
    "assetKey": "tankard-cluster",
    "category": "interior",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": true,
    "rawSize": [
      1.8999857306480408,
      1.092363953590393,
      0.9733815491199493
    ],
    "fittedSize": [
      1.9,
      1.092,
      0.973
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.546,
          0
        ],
        "half": [
          0.9,
          0.546,
          0.437
        ],
        "tags": [
          "obstacle",
          "provisional"
        ]
      }
    ]
  },
  "tavern-bar-barrels": {
    "assetKey": "tavern-bar-barrels",
    "category": "interior",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": true,
    "rawSize": [
      1.9000837206840515,
      0.837299257516861,
      0.6763876676559448
    ],
    "fittedSize": [
      1.9,
      0.837,
      0.676
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.419,
          0
        ],
        "half": [
          0.9,
          0.419,
          0.288
        ],
        "tags": [
          "obstacle",
          "provisional"
        ]
      }
    ]
  },
  "tavern-table-set": {
    "assetKey": "tavern-table-set",
    "category": "interior",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": true,
    "rawSize": [
      1.8974923491477966,
      1.1690399646759033,
      1.897358238697052
    ],
    "fittedSize": [
      1.897,
      1.169,
      1.897
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.585,
          0
        ],
        "half": [
          0.899,
          0.585,
          0.899
        ],
        "tags": [
          "obstacle",
          "provisional"
        ]
      }
    ]
  },
  "timber-crane": {
    "assetKey": "timber-crane",
    "category": "prop",
    "profile": "compound",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.750347375869751,
      1.898068606853485,
      0.9471962153911591
    ],
    "fittedSize": [
      3,
      3.253,
      1.623
    ],
    "colliders": [
      {
        "id": "base",
        "shape": "box",
        "center": [
          0,
          0.39,
          0
        ],
        "half": [
          0.9,
          0.39,
          0.649
        ],
        "tags": [
          "obstacle"
        ]
      },
      {
        "id": "mast",
        "shape": "capsule",
        "a": [
          0,
          0.28,
          0
        ],
        "b": [
          0,
          2.973,
          0
        ],
        "radius": 0.28,
        "tags": [
          "obstacle"
        ]
      }
    ]
  },
  "town-gate-wing-corner": {
    "assetKey": "town-gate-wing-corner",
    "category": "prop",
    "profile": "compound",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.9022204279899597,
      1.2568511366844177,
      1.9026483297348022
    ],
    "fittedSize": [
      1.902,
      1.257,
      1.903
    ],
    "colliders": [
      {
        "id": "wing-x",
        "shape": "box",
        "center": [
          0,
          0.629,
          -0.419
        ],
        "half": [
          0.951,
          0.629,
          0.152
        ],
        "tags": [
          "obstacle",
          "density-barrier"
        ]
      },
      {
        "id": "wing-z",
        "shape": "box",
        "center": [
          -0.418,
          0.629,
          0
        ],
        "half": [
          0.152,
          0.629,
          0.952
        ],
        "tags": [
          "obstacle",
          "density-barrier"
        ]
      }
    ]
  },
  "town-gate-wing-end": {
    "assetKey": "town-gate-wing-end",
    "category": "prop",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8975268006324768,
      0.9580993056297302,
      0.16341396421194077
    ],
    "fittedSize": [
      1.898,
      0.958,
      0.163
    ],
    "colliders": [
      {
        "id": "panel",
        "shape": "box",
        "center": [
          0,
          0.479,
          0
        ],
        "half": [
          0.929,
          0.479,
          0.082
        ],
        "tags": [
          "obstacle",
          "density-barrier"
        ]
      }
    ]
  },
  "town-gate-wing-straight": {
    "assetKey": "town-gate-wing-straight",
    "category": "prop",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8997054696083069,
      1.145587980747223,
      0.23117779195308685
    ],
    "fittedSize": [
      1.9,
      1.146,
      0.231
    ],
    "colliders": [
      {
        "id": "panel",
        "shape": "box",
        "center": [
          0,
          0.573,
          0
        ],
        "half": [
          0.93,
          0.573,
          0.116
        ],
        "tags": [
          "obstacle",
          "density-barrier"
        ]
      }
    ]
  },
  "type-cases": {
    "assetKey": "type-cases",
    "category": "interior",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": true,
    "rawSize": [
      1.900530457496643,
      1.8089390993118286,
      1.1042802333831787
    ],
    "fittedSize": [
      1.901,
      1.809,
      1.104
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.905,
          0
        ],
        "half": [
          0.901,
          0.905,
          0.502
        ],
        "tags": [
          "obstacle",
          "provisional"
        ]
      }
    ]
  },
  "washbasin-stand": {
    "assetKey": "washbasin-stand",
    "category": "interior",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": true,
    "rawSize": [
      1.1832528114318848,
      1.8992445468902588,
      1.1819984316825867
    ],
    "fittedSize": [
      1.183,
      1.899,
      1.182
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          0.95,
          0
        ],
        "half": [
          0.542,
          0.95,
          0.541
        ],
        "tags": [
          "obstacle",
          "provisional"
        ]
      }
    ]
  },
  "well-pump": {
    "assetKey": "well-pump",
    "category": "prop",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      0.9306577444076538,
      1.9024606943130493,
      1.0907313227653503
    ],
    "fittedSize": [
      1.272,
      2.6,
      1.491
    ],
    "colliders": [
      {
        "id": "body",
        "shape": "box",
        "center": [
          0,
          1.04,
          0
        ],
        "half": [
          0.586,
          1.04,
          0.696
        ],
        "tags": [
          "obstacle"
        ]
      }
    ]
  },
  "wharf-boardwalk-plank": {
    "assetKey": "wharf-boardwalk-plank",
    "category": "surface",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8991753458976746,
      0.1879696100950241,
      1.1341680884361267
    ],
    "fittedSize": [
      1.899,
      0.188,
      1.134
    ],
    "colliders": []
  },
  "wharf-pier-module": {
    "assetKey": "wharf-pier-module",
    "category": "surface",
    "profile": "none",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.9001864790916443,
      0.700887531042099,
      0.8826731741428375
    ],
    "fittedSize": [
      1.9,
      0.701,
      0.883
    ],
    "colliders": []
  },
  "wharf-rope-rail-corner": {
    "assetKey": "wharf-rope-rail-corner",
    "category": "prop",
    "profile": "compound",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8944745659828186,
      1.1848196983337402,
      1.9009540677070618
    ],
    "fittedSize": [
      1.894,
      1.185,
      1.901
    ],
    "colliders": [
      {
        "id": "wing-x",
        "shape": "box",
        "center": [
          0,
          0.593,
          -0.418
        ],
        "half": [
          0.947,
          0.593,
          0.152
        ],
        "tags": [
          "obstacle",
          "density-barrier"
        ]
      },
      {
        "id": "wing-z",
        "shape": "box",
        "center": [
          -0.417,
          0.593,
          0
        ],
        "half": [
          0.152,
          0.593,
          0.951
        ],
        "tags": [
          "obstacle",
          "density-barrier"
        ]
      }
    ]
  },
  "wharf-rope-rail-end": {
    "assetKey": "wharf-rope-rail-end",
    "category": "prop",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.9048446416854858,
      1.0691802501678467,
      0.4009948670864105
    ],
    "fittedSize": [
      1.905,
      1.069,
      0.401
    ],
    "colliders": [
      {
        "id": "panel",
        "shape": "box",
        "center": [
          0,
          0.535,
          0
        ],
        "half": [
          0.933,
          0.535,
          0.201
        ],
        "tags": [
          "obstacle",
          "density-barrier"
        ]
      }
    ]
  },
  "wharf-rope-rail-straight": {
    "assetKey": "wharf-rope-rail-straight",
    "category": "prop",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.904906988143921,
      0.5450961887836456,
      0.22327224910259247
    ],
    "fittedSize": [
      1.905,
      0.545,
      0.223
    ],
    "colliders": [
      {
        "id": "panel",
        "shape": "box",
        "center": [
          0,
          0.273,
          0
        ],
        "half": [
          0.933,
          0.273,
          0.112
        ],
        "tags": [
          "obstacle",
          "density-barrier"
        ]
      }
    ]
  },
  "work-ladder": {
    "assetKey": "work-ladder",
    "category": "prop",
    "profile": "compound",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      0.7823446094989777,
      1.9003046751022339,
      1.1397818326950073
    ],
    "fittedSize": [
      0.782,
      1.9,
      1.14
    ],
    "colliders": [
      {
        "id": "rail-l",
        "shape": "capsule",
        "a": [
          -0.219,
          0.04,
          0
        ],
        "b": [
          -0.219,
          1.86,
          0
        ],
        "radius": 0.04,
        "tags": [
          "obstacle",
          "ladder"
        ]
      },
      {
        "id": "rail-r",
        "shape": "capsule",
        "a": [
          0.219,
          0.04,
          0
        ],
        "b": [
          0.219,
          1.86,
          0
        ],
        "radius": 0.04,
        "tags": [
          "obstacle",
          "ladder"
        ]
      }
    ]
  },
  "yard-fence-corner": {
    "assetKey": "yard-fence-corner",
    "category": "prop",
    "profile": "compound",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8981208205223083,
      1.134178876876831,
      1.8344034552574158
    ],
    "fittedSize": [
      1.898,
      1.134,
      1.834
    ],
    "colliders": [
      {
        "id": "wing-x",
        "shape": "box",
        "center": [
          0,
          0.567,
          -0.403
        ],
        "half": [
          0.949,
          0.567,
          0.147
        ],
        "tags": [
          "obstacle",
          "density-barrier"
        ]
      },
      {
        "id": "wing-z",
        "shape": "box",
        "center": [
          -0.418,
          0.567,
          0
        ],
        "half": [
          0.152,
          0.567,
          0.917
        ],
        "tags": [
          "obstacle",
          "density-barrier"
        ]
      }
    ]
  },
  "yard-fence-end": {
    "assetKey": "yard-fence-end",
    "category": "prop",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.6603188514709473,
      1.898247480392456,
      0.3647630214691162
    ],
    "fittedSize": [
      1.66,
      1.898,
      0.365
    ],
    "colliders": [
      {
        "id": "panel",
        "shape": "box",
        "center": [
          0,
          0.949,
          0
        ],
        "half": [
          0.81,
          0.949,
          0.183
        ],
        "tags": [
          "obstacle",
          "density-barrier"
        ]
      }
    ]
  },
  "yard-fence-gate": {
    "assetKey": "yard-fence-gate",
    "category": "prop",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.900612235069275,
      0.8043085038661957,
      0.1501385197043419
    ],
    "fittedSize": [
      1.901,
      0.804,
      0.15
    ],
    "colliders": [
      {
        "id": "panel",
        "shape": "box",
        "center": [
          0,
          0.402,
          0
        ],
        "half": [
          0.931,
          0.402,
          0.075
        ],
        "tags": [
          "obstacle",
          "density-barrier"
        ]
      }
    ]
  },
  "yard-fence-straight": {
    "assetKey": "yard-fence-straight",
    "category": "prop",
    "profile": "solid",
    "pendingDoorContract": false,
    "pendingInteriorPlacement": false,
    "rawSize": [
      1.8994674682617188,
      0.9797655045986176,
      0.1566021665930748
    ],
    "fittedSize": [
      1.899,
      0.98,
      0.157
    ],
    "colliders": [
      {
        "id": "panel",
        "shape": "box",
        "center": [
          0,
          0.49,
          0
        ],
        "half": [
          0.93,
          0.49,
          0.079
        ],
        "tags": [
          "obstacle",
          "density-barrier"
        ]
      }
    ]
  }
};
